export const skills = [
	{ name: "html", alt: "HTML" },
	{ name: "css", alt: "CSS" },
	{ name: "js", alt: "JavaScript" },
	{ name: "bootstrap", alt: "Bootstrap" },
	{ name: "sass", alt: "Sass" },
	{ name: "jquery", alt: "JQuery" },
	{ name: "react", alt: "React" },
	{ name: "redux", alt: "Redux" },
	{ name: "styled", alt: "Styled Components" },
	{ name: "next", alt: "Next.js" },
	{ name: "firebase", alt: "Firebase" },
	{ name: "git", alt: "Git" },
	{ name: "figma", alt: "Figma" },
];
